<button id="btn-modal">
    <span><?= $block->escapeHtml(__('Open Modal')) ?></span>
</button>
<button id="btn-login-modal">
    <span><?= $block->escapeHtml(__('Open Magento Login Modal')) ?></span>
</button>
<button id="btn-custom-login-modal">
    <span><?= $block->escapeHtml(__('Open Custom Login Modal')) ?></span>
</button>

<div id="modal">
    <div class="modal-body-content">
        <h3><?= $block->escapeHtml(__('Hello World')) ?></h3>
    </div>
</div>

<div id="custom-modal">
    <div class="modal-body-content">
        <div class="block block-customer-login">
            <div class="block-content" aria-labelledby="block-customer-login-heading">
                <form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="login-form" data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <div class="field email required">
                            <div class="control">
                                <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <div class="control">
                                <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                        <div class="actions-toolbar">
                            <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Login')) ?></span></button></div>
                            <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require([
            "jquery",
            "Magento_Ui/js/modal/modal"
        ], function($, modal) {

            $('#btn-modal').click(function() {
                alert('Hello World');
            });

            var options = {
                title: 'Login Modal',
                responsive: true,
                buttons: [{
                    text: $.mage.__('Ok'),
                    class: '',
                    click: function() {
                        this.closeModal();
                    }
                }]
            };

            var options_custom = {
                title: 'Login Modal',
                responsive: true,
                buttons: []
            };

            var popup = modal(options, $('#modal'));
            $("#btn-login-modal").click(function() {
                $('#modal').modal('openModal');
            });

            var popup_custom = modal(options_custom, $('#custom-modal'));
            $("#btn-custom-login-modal").click(function() {
                $('#custom-modal').modal('openModal');
            });
        });
    </script>